#%RAML 1.0
---
title: peanuts API
mediaType: application/json
baseUri: None

types:
    hash64:
        type: string
        pattern: "[a-zA-Z0-9]{64}"
    block: !include types/block.raml
    component: !include types/component.raml
    user: !include types/user.raml

annotationTypes:
    implementer:
        allowedTargets: Method
        type: component
    client_name:
        allowedTargets: Method
        type: string

/blockchain:
    get:
        (client_name): blockchain.get_info
        (implementer): btcwrapp
        description: Get summary information about the blockchain
        responses:
            200:
                body:
                    application/json:
/block:
    get:
        (client_name): block.get_best_block
        (implementer): btcwrapp
        description: Get summary information for the best (most recent) block
        responses:
            200:
                application/json:
                    type: block
    /{hash}:
        get:
            (client_name): block.get
            (implementer): btcwrapp
            description: Get summary informaiton about a particular block
            responses:
                200:
                    application/json:
                        type: block
/user:
    post:
        (client_name): user.create
        (implementer): dirt
        description: Create a new user
        body:
            application/json:
                type: user
    /{user_id}:
        get:
            (client_name): user.get
            (implementer): dirt
            description: Retrieve a user
            responses:
                200:
                    application/json:
                        type: user