#%RAML 1.0

type: object
properties:
    bits: string
    chainwork: hash64
    confirmations: integer
    difficulty: number
    hash: hash64
    height: integer
    mediantime: integer
    merkleroot: hash64
    nTx: integer
    nextblockhash: hash64
    nonce: integer
    previousblockhash: hash64
    size: integer
    strippedsize: integer
    time: integer
    tx: string[]
    version: integer
    versionHex: string
    weight: integer